version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    container_name: app
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    env_file:
      - ./secrets/.env
    volumes:
      - .:/code
      - python-packages:/usr/local/lib/python3.10/site-packages
      - python-bin:/usr/local/bin
    command: /bin/bash scripts/start-dev.sh
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    container_name: worker
    depends_on:
      - redis
    env_file:
      - ./secrets/.env
    volumes:
      - .:/code
      - python-packages:/usr/local/lib/python3.10/site-packages
      - python-bin:/usr/local/bin
    command: /bin/bash scripts/start-worker.sh
    
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-volume:/data/postgres/:/var/lib/postgresql/data
  
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data/redis/:/data
volumes:
  python-packages:
  python-bin:
  db-volume:
  redis-volume:


